//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIAL
    {
        public int idHistorial { get; set; }
        public int idUsuario { get; set; }
        public int idSubCaso { get; set; }
        public int idMovimiento { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual MOVIMIENTO MOVIMIENTO { get; set; }
        public virtual SUBCASO SUBCASO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
