//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Huellas_Dactilares
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Huellas_Dactilares()
        {
            this.RESULTADOS = new HashSet<RESULTADOS>();
        }
    
        public int idDactilar { get; set; }
        public string Nombre { get; set; }
        public string Apellido_P { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> Fecha_nac { get; set; }
        public byte[] Imagen { get; set; }
        public string Path_imagen { get; set; }
        public string REGION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESULTADOS> RESULTADOS { get; set; }
    }
}
