//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegrador.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Modulo_IdentificacionEntities : DbContext
    {
        public Modulo_IdentificacionEntities()
            : base("name=Modulo_IdentificacionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CASO> CASO { get; set; }
        public virtual DbSet<HISTORIAL> HISTORIAL { get; set; }
        public virtual DbSet<Huellas_Dactilares> Huellas_Dactilares { get; set; }
        public virtual DbSet<Huellas_Palmares> Huellas_Palmares { get; set; }
        public virtual DbSet<IDENTIFICACION> IDENTIFICACION { get; set; }
        public virtual DbSet<LATENTE> LATENTE { get; set; }
        public virtual DbSet<LICENCIA> LICENCIA { get; set; }
        public virtual DbSet<MOVIMIENTO> MOVIMIENTO { get; set; }
        public virtual DbSet<RESULTADOS> RESULTADOS { get; set; }
        public virtual DbSet<SUBCASO> SUBCASO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    
        public virtual ObjectResult<CONSULT_HISTORY_Result> CONSULT_HISTORY(Nullable<int> user_id)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CONSULT_HISTORY_Result>("CONSULT_HISTORY", user_idParameter);
        }
    
        public virtual ObjectResult<GET_SAVED_IDENTIFICATIONS_Result> GET_SAVED_IDENTIFICATIONS(Nullable<int> idIdentificacion)
        {
            var idIdentificacionParameter = idIdentificacion.HasValue ?
                new ObjectParameter("idIdentificacion", idIdentificacion) :
                new ObjectParameter("idIdentificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_SAVED_IDENTIFICATIONS_Result>("GET_SAVED_IDENTIFICATIONS", idIdentificacionParameter);
        }
    
        public virtual ObjectResult<GET_SUBCASES_Result> GET_SUBCASES(Nullable<int> case_id)
        {
            var case_idParameter = case_id.HasValue ?
                new ObjectParameter("case_id", case_id) :
                new ObjectParameter("case_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_SUBCASES_Result>("GET_SUBCASES", case_idParameter);
        }
    }
}
