//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESULTADOS
    {
        public int idResultado { get; set; }
        public int idIdentificacion { get; set; }
        public int idSubcaso { get; set; }
        public Nullable<int> idHuellaPalmar { get; set; }
        public Nullable<int> idHuellaDactilar { get; set; }
        public string Resultado { get; set; }
    
        public virtual Huellas_Dactilares Huellas_Dactilares { get; set; }
        public virtual Huellas_Palmares Huellas_Palmares { get; set; }
        public virtual IDENTIFICACION IDENTIFICACION { get; set; }
    }
}
