//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBCASO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUBCASO()
        {
            this.HISTORIAL = new HashSet<HISTORIAL>();
            this.IDENTIFICACION = new HashSet<IDENTIFICACION>();
        }
    
        public int idSubcaso { get; set; }
        public Nullable<int> idHuella { get; set; }
        public Nullable<int> idCaso { get; set; }
        public string DESCRIPCION { get; set; }
        public string IDENTIFICADOR { get; set; }
    
        public virtual CASO CASO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIAL> HISTORIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IDENTIFICACION> IDENTIFICACION { get; set; }
        public virtual LATENTE LATENTE { get; set; }
    }
}
