//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.HISTORIAL = new HashSet<HISTORIAL>();
        }
    
        public int idUsuario { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public string Organizacion { get; set; }
        public Nullable<int> Creditos { get; set; }
        public Nullable<System.DateTime> Fecha_nacimiento { get; set; }
        public Nullable<int> idLicencia { get; set; }
        public Nullable<System.DateTime> Inicio_Licencia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIAL> HISTORIAL { get; set; }
        public virtual LICENCIA LICENCIA { get; set; }
    }
}
